apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ingestion-streamer.fullname" . }}
  labels:
    {{- include "ingestion-streamer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ingestion-streamer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ingestion-streamer.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                  key: {{ .Values.secrets.projectId }}
            - name: KITE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                  key: {{ .Values.secrets.kiteApiKey }}
            - name: KITE_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                  key: {{ .Values.secrets.kiteApiSecret }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
