apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "execution-api.fullname" . }}
  labels:
    {{- include "execution-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "execution-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "execution-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: VERTEX_AI_PROJECT
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                  key: {{ .Values.secrets.vertexAiProject }}
            - name: VERTEX_AI_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                  key: {{ .Values.secrets.vertexAiRegion }}
            - name: VERTEX_AI_ENDPOINT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                  key: {{ .Values.secrets.vertexAiEndpointId }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
